deploy:
  needs: build-and-test
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/main' && github.event_name == 'push'

  steps:
    # 1. Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4 # Updated to the latest version

    # 2. Set up Node.js environment
    - name: Use Node.js
      uses: actions/setup-node@v4 # Updated to the latest version
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './shopy-pwa/package-lock.json'

    # 3. Install dependencies (use npm ci for clean, faster install)
    - name: Install dependencies
      working-directory: ./shopy-pwa
      run: npm ci

    # 4. Build the application
    - name: Build application
      working-directory: ./shopy-pwa
      run: npm run build

    # 5. Debug step (optional but useful for deployment failures)
    - name: Debug: Verify files
      working-directory: ./shopy-pwa
      run: |
        echo "Current directory contents:"
        ls -la

    # 6. Deploy to Vercel
    - name: Deploy to Vercel
      working-directory: ./shopy-pwa
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      run: |
        npx vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} --cwd ./shopy-pwa --yes
